<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit48f43e074594501f1ce4b434d8fe58a9
{
    public static $prefixLengthsPsr4 = array (
        'L' => 
        array (
            'Lesptitnours\\Popotes\\' => 21,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Lesptitnours\\Popotes\\' => 
        array (
            0 => __DIR__ . '/../..' . '/includes',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit48f43e074594501f1ce4b434d8fe58a9::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit48f43e074594501f1ce4b434d8fe58a9::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit48f43e074594501f1ce4b434d8fe58a9::$classMap;

        }, null, ClassLoader::class);
    }
}
